import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Roboto({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-global",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Navbar />
        {/* <ImagePreloader /> */}
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
